packages:
  - "."
allowBuilds:
  better-sqlite3: true
  esbuild: true
peerDependencyRules:
  allowedVersions:
    "eslint-plugin-jsx-a11y>eslint": "10"
overrides:
  katex: "0.18.1"
minimumReleaseAgeExclude:
  - "@better-auth/core@1.6.25"
  - "@better-auth/drizzle-adapter@1.6.25"
  - "@better-auth/kysely-adapter@1.6.25"
  - "@better-auth/memory-adapter@1.6.25"
  - "@better-auth/mongo-adapter@1.6.25"
  - "@better-auth/passkey@1.6.25"
  - "@better-auth/prisma-adapter@1.6.25"
  - "@better-auth/telemetry@1.6.25"
  - better-auth@1.6.25
